"""Go/no-go for the retrieval redesign. CPU only, no GPU, no model loading.

THE QUESTION
------------
MA-RAG's four roles exist to issue repeated targeted queries against ~21M
Wikipedia passages. Our SPEC §3 deleted the retriever and hands the Extractor a
fixed 10 paragraphs, so the Step Definer's `search_terms` field is consumed by
nothing and decomposition has no mechanism through which to help. That is why
`single_fp16` beats the four-agent pipeline by 9.2 EM: with both gold paragraphs
guaranteed present, there is nothing to find.

Pooling every unique paragraph in the HotpotQA dev split gives a 66,581-passage
corpus with 2 gold per question. This script measures whether that restores the
mechanism, by comparing:

    SINGLE : one BM25 query = the original multi-hop question
    MULTI  : one BM25 query per sub-question, results unioned

using the REAL planner sub-questions already generated by the n=3000 baseline
run, so the comparison reflects the plans the model actually produces rather
than idealised ones.

DECISION RULE, fixed before looking
-----------------------------------
  * If SINGLE recall@k is already very high (>0.90), the haystack is too easy.
    Decomposition has no headroom and the redesign does not help. NO-GO.
  * If MULTI recall@k materially exceeds SINGLE, decomposition buys retrieval
    coverage and the redesign restores the mechanism. GO.
  * If both are low and equal, BM25 is too weak on this corpus and the ceiling
    drops for every arm. NO-GO for BM25 (would need dense retrieval).
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

_TOKEN = re.compile(r"[a-z0-9]+")


def tok(s: str) -> list[str]:
    return _TOKEN.findall(s.lower())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=1000, help="questions to evaluate")
    ap.add_argument("--ks", default="5,10,20,50")
    ap.add_argument("--plans", default="results/baseline_qwen2.5-1.5b_n3000_seed7.jsonl",
                    help="a completed run whose planner outputs supply real sub-questions")
    args = ap.parse_args()
    ks = [int(k) for k in args.ks.split(",")]

    from datasets import load_dataset
    from rank_bm25 import BM25Okapi

    ds = load_dataset("hotpotqa/hotpot_qa", "distractor", split="validation")

    # ---- corpus: every unique paragraph in the split, keyed by title --------
    para: dict[str, str] = {}
    for row in ds:
        for t, sents in zip(row["context"]["title"], row["context"]["sentences"]):
            if t not in para:
                para[t] = " ".join(sents)
    titles = list(para)
    print(f"corpus: {len(titles):,} unique passages")

    print("indexing BM25 (CPU)...", flush=True)
    bm25 = BM25Okapi([tok(para[t]) for t in titles])
    print("indexed.\n")

    # ---- real sub-questions from a completed run ---------------------------
    plans: dict[str, list[str]] = {}
    p = Path(args.plans)
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            if '"planner"' not in line:
                continue
            r = json.loads(line)
            if r.get("stage") != "planner":
                continue
            got = (r.get("parsed") or {}).get("sub_questions")
            if got:
                plans[r["question_id"]] = got[:3]
        print(f"real planner sub-questions available for {len(plans):,} questions")
    else:
        print(f"!! {p} not found — falling back to gold-decomposition-free mode")

    gold = {row["id"]: set(row["supporting_facts"]["title"]) for row in ds}
    qtext = {row["id"]: row["question"] for row in ds}

    qids = [q for q in qtext if q in plans][: args.n]
    if not qids:
        qids = list(qtext)[: args.n]
    print(f"evaluating {len(qids):,} questions\n")

    hits = defaultdict(lambda: defaultdict(float))
    nsub = 0
    for i, qid in enumerate(qids):
        if i and i % 200 == 0:
            print(f"  {i}/{len(qids)}", flush=True)
        g = gold[qid]
        if not g:
            continue
        subs = plans.get(qid, [])
        nsub += len(subs)

        single_rank = bm25.get_top_n(tok(qtext[qid]), titles, n=max(ks))
        per_sub = [bm25.get_top_n(tok(s), titles, n=max(ks)) for s in subs] or [single_rank]

        for k in ks:
            s_at_k = set(single_rank[:k])
            hits[k]["single"] += len(g & s_at_k) / len(g)
            hits[k]["single_all"] += float(g <= s_at_k)

            # MULTI: union of top-(k/|subs|) per sub-question, so the two arms
            # read the SAME number of passages. Otherwise multi wins trivially
            # by being shown more text.
            per = max(1, k // max(len(per_sub), 1))
            u = set()
            for ranked in per_sub:
                u |= set(ranked[:per])
            hits[k]["multi"] += len(g & u) / len(g)
            hits[k]["multi_all"] += float(g <= u)

            # MULTI-BUDGETED: each sub-question gets a full k (multi reads more
            # text, which costs more tokens — reported so the trade is visible).
            u2 = set()
            for ranked in per_sub:
                u2 |= set(ranked[:k])
            hits[k]["multi_fullk"] += len(g & u2) / len(g)
            hits[k]["multi_fullk_all"] += float(g <= u2)

    n = len(qids)
    print(f"\nmean sub-questions/question: {nsub / n:.2f}\n")
    print(f"{'k':>4}  {'SINGLE gold-recall':>19}{'both-gold':>11}   "
          f"{'MULTI (same budget)':>20}{'both-gold':>11}   {'MULTI (k each)':>16}{'both-gold':>11}")
    for k in ks:
        h = hits[k]
        print(f"{k:>4}  {h['single']/n:>19.3f}{h['single_all']/n:>11.3f}   "
              f"{h['multi']/n:>20.3f}{h['multi_all']/n:>11.3f}   "
              f"{h['multi_fullk']/n:>16.3f}{h['multi_fullk_all']/n:>11.3f}")

    print("\n--- verdict inputs ---")
    for k in ks:
        h = hits[k]
        s, m, f = h["single"] / n, h["multi"] / n, h["multi_fullk"] / n
        print(f"  k={k:<3} single {s:.3f} | multi(same budget) {m:+.3f} ({m - s:+.3f}) "
              f"| multi(k each) {f:.3f} ({f - s:+.3f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
